{
 "title": "NVIDIA DCGM Exporter Dashboard",
 "description": "This dashboard is to display the metrics from DCGM Exporter on a Kubernetes (1.19+) cluster",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(DCGM_FI_DEV_GPU_TEMP, instance)"
   },
   {
    "name": "gpu",
    "query": "label_values(DCGM_FI_DEV_GPU_TEMP, gpu)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP{instance=\"$instance\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (instance, gpu) (\r\n  DCGM_FI_DEV_GPU_TEMP{instance=~\"$instance\", gpu=~\"$gpu\", pod=~\"$pod\"}\r\n)\r\n",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "gauge",
   "description": "avg temp per gpu",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (instance, gpu) (\r\n  DCGM_FI_DEV_GPU_TEMP{instance=~\"$instance\", gpu=~\"$gpu\", pod=~\"$pod\"}\r\n)\r\n",
     "legendFormat": "GPU: {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "max by (instance, gpu) (\r\n  DCGM_FI_DEV_POWER_USAGE{\r\n    instance=~\"$instance\",\r\n    gpu=~\"$gpu\",\r\n    pod=~\"$pod\"\r\n  }\r\n)\r\n",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Power Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (instance, gpu) (\r\n  DCGM_FI_DEV_POWER_USAGE{\r\n    instance=~\"$instance\",\r\n    gpu=~\"$gpu\",\r\n    pod=~\"$pod\"\r\n  }\r\n)\r\n",
     "legendFormat": "GPU: {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "max by (instance, gpu) (\r\n  DCGM_FI_DEV_SM_CLOCK{\r\n    instance=~\"$instance\",\r\n    gpu=~\"$gpu\",\r\n    pod=~\"$pod\"\r\n  }\r\n) * 1000000\r\n",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (instance, gpu) (\r\n  DCGM_FI_DEV_GPU_UTIL{\r\n    instance=~\"$instance\",\r\n    gpu=~\"$gpu\",\r\n    pod=~\"$pod\"\r\n  }\r\n)\r\n",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Tensor Core Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (instance, gpu) (\r\n  DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{\r\n    instance=~\"$instance\",\r\n    gpu=~\"$gpu\",\r\n    pod=~\"$pod\"\r\n  }\r\n)\r\n",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Mem Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "max by (instance, gpu) (\r\n  DCGM_FI_DEV_FB_USED{\r\n    instance=~\"$instance\",\r\n    gpu=~\"$gpu\",\r\n    pod=~\"$pod\"\r\n  }\r\n)\r\n",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  }
 ]
}