{
 "title": "gorush Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(gorush_submitted_tasks{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(gorush_total_push_count{namespace=\"$namespace\"},pod)"
    }
   },
   { "name": "search", "label": "search" },
   { "name": "platform", "query": "android,ios,huawei" },
   {
    "name": "err_re",
    "label": "err_re",
    "query": "error|err=|fatal|panic|exception"
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success rate (%)",
   "type": "stat",
   "description": "глобальный success rate (по умолчанию 100)",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\r\n  100 *\r\n  (sum(increase(gorush_failure_tasks{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__range])) or vector(0))\r\n  /\r\n  clamp_min(\r\n    (\r\n      (sum(increase(gorush_success_tasks{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__range])) or vector(0))\r\n    + (sum(increase(gorush_failure_tasks{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__range])) or vector(0))\r\n    ),\r\n    1\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "round(sum(increase(gorush_submitted_tasks{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])))\r\n",
     "legendFormat": "call submitted tasks"
    },
    {
     "expr": "round(sum(increase(gorush_success_tasks{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])))",
     "legendFormat": "call success tasks"
    },
    {
     "expr": "round(sum(increase(gorush_failure_tasks{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])))",
     "legendFormat": "call failure tasks"
    }
   ]
  },
  {
   "title": "Push throughput",
   "type": "stat",
   "description": "сколько  пушей  было получено за N период времени.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\r\n  sum(increase(gorush_total_push_count{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__range]))\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Busy workers",
   "type": "stat",
   "description": "рабочие воркеры в данный момент",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(gorush_busy_workers{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last logs",
   "type": "logs",
   "description": "поcледние логи\n(по поду на текущий момент нет(не знаю нужно ли или нет))",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"gorush\", cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Last errors",
   "type": "logs",
   "description": "поcледние ошибки\n(по поду на текущий момент нет(не знаю нужно ли или нет))",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"gorush\", cluster=~\"$cluster\"}\r\n|~ \"(?i)(${search}|$err_re)\""
    }
   ]
  },
  {
   "title": "${platform} throughput: success vs fail / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "round(sum(increase(gorush_${platform}_success{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])))",
     "legendFormat": "${platform} success calls"
    },
    {
     "expr": "round(\r\n  sum(\r\n    increase(gorush_${platform}_fail{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])\r\n    or\r\n    increase(gorush_${platform}_error{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])\r\n  )\r\n)\r\n",
     "legendFormat": "${platform} fail calls"
    }
   ]
  }
 ]
}