{
 "title": "gorush Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(gorush_submitted_tasks{cluster=\"$cluster\"},instance)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(gorush_total_push_count{instance=\"$node\"},pod)"
    }
   },
   { "name": "search", "label": "search", "query": "failed" }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error rate (%)",
   "type": "timeseries",
   "description": "общий процент ошибок в задачах",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "100 *\r\nsum(rate(gorush_failure_tasks{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms]))\r\n/\r\nclamp_min(\r\n  sum(rate(gorush_success_tasks{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms])) + sum(rate(gorush_failure_tasks{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms])),\r\n  1\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success rate (%)",
   "type": "gauge",
   "description": "глобальный success rate",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum(rate(gorush_success_tasks{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms]))\r\n/\r\nclamp_min(\r\n  sum(rate(gorush_success_tasks{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms])) + sum(rate(gorush_failure_tasks{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms])),\r\n  1\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Push throughput",
   "type": "gauge",
   "description": "сколько пушей/сек",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gorush_total_push_count{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Busy workers",
   "type": "gauge",
   "description": "рабочие воркеры в данный момент",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gorush_busy_workers{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(gorush_submitted_tasks{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms])\r\n",
     "legendFormat": "rate submitted tasks"
    },
    {
     "expr": "rate(gorush_success_tasks{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms])",
     "legendFormat": "rate success tasks"
    },
    {
     "expr": "rate(gorush_failure_tasks{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms])",
     "legendFormat": "rate failure tasks"
    }
   ]
  },
  {
   "title": "Backlog “submitted - (success+failure)”",
   "type": "timeseries",
   "description": "за выбранное окно времени мы догоняем или отстаём",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(gorush_submitted_tasks{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms]))\r\n-\r\nsum(increase(gorush_success_tasks{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms]))\r\n-\r\nsum(increase(gorush_failure_tasks{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last errors",
   "type": "logs",
   "description": "поcледние ошибки",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"gorush\", cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}\r\n|~ \"(?i)(${search}|error|err=|fatal|panic|exception)\"\r\n"
    }
   ]
  },
  { "title": "Android", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Android throughput: success vs fail / sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(gorush_android_success{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms]))",
     "legendFormat": "android success rate"
    },
    {
     "expr": "sum(rate(gorush_android_fail{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms]))",
     "legendFormat": "android fail rate"
    }
   ]
  },
  {
   "title": "Android success rate (%)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 9, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum(rate(gorush_android_success{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms]))\r\n/\r\nclamp_min(\r\n  sum(rate(gorush_android_success{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms]))\r\n+ sum(rate(gorush_android_fail{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms])),\r\n  1\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Android fails by pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 25 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(gorush_android_fail{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "IOS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "IOS throughput: success vs fail / sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(gorush_ios_success{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms]))",
     "legendFormat": "ios success rate"
    },
    {
     "expr": "sum(rate(gorush_ios_error{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms]))",
     "legendFormat": "ios fail rate"
    }
   ]
  },
  {
   "title": "IOS success rate (%)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 9, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum(rate(gorush_ios_success{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms]))\r\n/\r\nclamp_min(\r\n  sum(rate(gorush_ios_success{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms]))\r\n+ sum(rate(gorush_ios_fail{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms])),\r\n  1\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IOS fails by pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 35 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(gorush_ios_fail{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Huawei", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Huawei throughput: success vs fail / sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(gorush_huawei_success{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms]))",
     "legendFormat": "huawei success rate"
    },
    {
     "expr": "sum(rate(gorush_huawei_fail{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms]))",
     "legendFormat": "huawei fail rate"
    }
   ]
  },
  {
   "title": "Huawei success rate (%)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 9, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum(rate(gorush_huawei_success{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms]))\r\n/\r\nclamp_min(\r\n  sum(rate(gorush_huawei_success{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms]))\r\n+ sum(rate(gorush_huawei_fail{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms])),\r\n  1\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Huawei fails by pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 45 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(gorush_huawei_fail{cluster=~\"$cluster\", instance=~\"$node\", pod=~\"$pod\"}[$__rate_interval_ms]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}