{
 "title": "NGINX Monitoring",
 "tags": [ "nginx" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"$job\"} [1m])"
    }
   ]
  },
  {
   "title": "Latest NGINX Errors",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"$job\"} |= \"error\""
    }
   ]
  },
  {
   "title": "4xx errors per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n    {job=\"$job\"}\r\n    | pattern \"<ip> - - [<timestamp>] \\\"<method> <path> <protocol>\\\" <status> <size> \\\"<referrer>\\\" \\\"<user_agent>\\\" <req_len> <req_time> [<upstream>] [<unknown>] <rest>\"\r\n    | status=~\"4..\"\r\n    [1m]\r\n  )\r\n)",
     "legendFormat": "Errors 4**"
    }
   ]
  },
  {
   "title": "4xx Responses ",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"$job\"}\r\n| pattern \"<ip> - - [<timestamp>] \\\"<method> <path> <protocol>\\\" <status> <size> \\\"<referrer>\\\" \\\"<user_agent>\\\" <req_len> <req_time> [<upstream>] [<unknown>] <rest>\"\r\n| status=~\"4..\"\r\n| line_format \"{{.status}} {{.method}} {{.path}} time={{.req_time}}\"\r\n"
    }
   ]
  },
  {
   "title": "5xx errors per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n    {job=\"$job\"}\r\n    | pattern \"<ip> - - [<timestamp>] \\\"<method> <path> <protocol>\\\" <status> <size> \\\"<referrer>\\\" \\\"<user_agent>\\\" <req_len> <req_time> [<upstream>] [<unknown>] <rest>\"\r\n    | status=~\"5..\"\r\n    [1m]\r\n  )\r\n)",
     "legendFormat": "Errors 5**"
    }
   ]
  },
  {
   "title": "5xx Responses",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"$job\"}\r\n| pattern \"<ip> - - [<timestamp>] \\\"<method> <path> <protocol>\\\" <status> <size> \\\"<referrer>\\\" \\\"<user_agent>\\\" <req_len> <req_time> [<upstream>] [<unknown>] <rest>\"\r\n| status=~\"5..\"\r\n| line_format \"{{.status}} {{.method}} {{.path}} time={{.req_time}}\""
    }
   ]
  },
  {
   "title": "2xx status code per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n    {job=\"$job\"}\r\n    | pattern \"<ip> - - [<timestamp>] \\\"<method> <path> <protocol>\\\" <status> <size> \\\"<referrer>\\\" \\\"<user_agent>\\\" <req_len> <req_time> [<upstream>] [<unknown>] <rest>\"\r\n    | status=~\"2..\"\r\n    [1m]\r\n  )\r\n)",
     "legendFormat": "Status 2**"
    }
   ]
  },
  {
   "title": "2xx Responses ",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"$job\"}\r\n| pattern \"<ip> - - [<timestamp>] \\\"<method> <path> <protocol>\\\" <status> <size> \\\"<referrer>\\\" \\\"<user_agent>\\\" <req_len> <req_time> [<upstream>] [<unknown>] <rest>\"\r\n| status=~\"2..\"\r\n| line_format \"{{.status}} {{.method}} {{.path}} time={{.req_time}}\"\r\n"
    }
   ]
  }
 ]
}