{
 "title": "PostgresExporter monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": {
     "query": "label_values({job=\"integrations/postgres-exporter\"},instance)"
    }
   },
   { "name": "Database", "query": { "query": "label_values(datname)" } },
   {
    "name": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query rate",
     "type": "stat",
     "description": "Statements executed per Minute.\n\nSource: pg_stat_statements.calls",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((rate(pg_stat_statements_calls_total{instance=\"$Instance\"}[$Interval])))"
      }
     ]
    },
    {
     "title": "Shared Buffers",
     "type": "stat",
     "description": "Setting: shared_buffers in PostgreSQL.conf",
     "gridPos": { "h": 4, "w": 4, "x": 5, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_shared_buffers_bytes{instance=\"$Instance\"}"
      }
     ]
    },
    {
     "title": "Shared Buffer Hits",
     "type": "gauge",
     "description": "Shared buffer hits vs reads from disc",
     "gridPos": { "h": 8, "w": 5, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_database_blks_hit{instance=~\"$Instance\"})/(sum(pg_stat_database_blks_hit{instance=~\"$Instance\"})+sum(pg_stat_database_blks_read{instance=~\"$Instance\"}))*100"
      }
     ]
    },
    {
     "title": "Connections used",
     "type": "gauge",
     "description": "Percentage of max_connections used",
     "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_database_numbackends)/max(pg_settings_max_connections)"
      }
     ]
    },
    {
     "title": "Commit Ratio",
     "type": "gauge",
     "description": "Transaction committed vs rollbacked",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_database_xact_commit{instance=\"$Instance\"})/(sum(pg_stat_database_xact_commit{instance=\"$Instance\"}) + sum(pg_stat_database_xact_rollback{instance=\"$Instance\"}))"
      }
     ]
    },
    {
     "title": "Transaction rate",
     "type": "stat",
     "description": "Transactions committed + roolback per minute\n\nSource: pg_stat_database,xact_commit + xact_rollback",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((rate(pg_stat_database_xact_commit{instance=\"$Instance\"}[$Interval])))+sum((rate(pg_stat_database_xact_rollback{instance=\"$Instance\"}[$Interval])))"
      }
     ]
    },
    {
     "title": "Max Replication Lag",
     "type": "stat",
     "description": "Max Replication lag behind master in seconds\n\nOnly available on a standby system.\n\nSource: pg_last_xact_replay_timestamp\n\nUse: pg_stat_replication for Details.",
     "gridPos": { "h": 4, "w": 4, "x": 5, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(pg_replication_lag_seconds{instance=\"$Instance\"})"
      }
     ]
    },
    {
     "title": "Max Connections",
     "type": "stat",
     "description": "Setting: max_connections in postgreSQL.conf",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_connections{instance=\"$Instance\"}"
      }
     ]
    },
    {
     "title": "Connections to bases",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 169 },
     "targets": [
      {
       "expr": "pg_stat_database_numbackends{datname=~\"$Database\", instance=~\"$Instance\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Connections by database (stacked)",
     "type": "timeseries",
     "description": "View: pg_stat_activity",
     "gridPos": { "h": 8, "w": 19, "x": 0, "y": 176 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (datname) (\r\n  pg_stat_database_numbackends{instance=~\"$Instance\", datname=~\"$Database\"}\r\n)",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total database size",
     "type": "stat",
     "description": "Size of all databases in $Instance.\n\nSource: pg_database_size()",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 176 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_database_size_bytes{instance=\"$Instance\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions",
     "type": "timeseries",
     "description": "1 Minute rate of transactions committed or rollback.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 217 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum ((rate(pg_stat_database_xact_commit[$Interval])))",
       "legendFormat": "committed"
      },
      {
       "expr": "sum ((rate(pg_stat_database_xact_rollback[$Interval])))",
       "legendFormat": "rollback"
      }
     ]
    },
    {
     "title": "Tuples inserts/updates/deletes",
     "type": "timeseries",
     "description": "Source: pg_stat_database",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 256 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum((rate(pg_stat_database_tup_inserted{instance=\"$Instance\"}[$Interval])))",
       "legendFormat": "Inserts"
      },
      {
       "expr": "sum((rate(pg_stat_database_tup_updated{instance=\"$Instance\"}[$Interval])))",
       "legendFormat": "Updates"
      },
      {
       "expr": "sum((rate(pg_stat_database_tup_deleted{instance=\"$Instance\"}[$Interval])))",
       "legendFormat": "Deletes"
      }
     ]
    },
    {
     "title": "Longest transition",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 256 },
     "targets": [
      {
       "expr": "time() - pg_long_running_transactions_oldest_timestamp_seconds",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "I/O Read/Write time",
     "type": "timeseries",
     "description": "* blk_read_time: Time spent reading data file blocks by backends in this database, in milliseconds\n* blk_write_time: Time spent writing data file blocks by backends in this database, in milliseconds\n\ntrack_io_timings needs to be activated",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 263 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum ((rate(pg_stat_database_blk_read_time{instance=\"$Instance\"}[$Interval])))",
       "legendFormat": "blk_read_time"
      },
      {
       "expr": "sum ((rate(pg_stat_database_blk_write_time{instance=\"$Instance\"}[$Interval])))",
       "legendFormat": "blk_read_time"
      }
     ]
    },
    {
     "title": "Tuples fetched/returned",
     "type": "timeseries",
     "description": "Source: pg_stat_database\n\n* tup_fetched: rows needed to satisfy queries\n* tup_returned: rows read/scanned",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 263 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum((rate(pg_stat_database_tup_fetched{instance=\"$Instance\"}[$Interval])))",
       "legendFormat": "Fetched"
      },
      {
       "expr": "sum((rate(pg_stat_database_tup_returned{instance=\"$Instance\"}[$Interval])))",
       "legendFormat": "Returned"
      }
     ]
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Slowest Queries by Average Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "topk(5,\r\n  (\r\n    pg_stat_statements_seconds_total{datname=~\"$Database\", instance=~\"$Instance\"}\r\n    /\r\n    pg_stat_statements_calls_total{datname=~\"$Database\", instance=~\"$Instance\"}\r\n  )\r\n)\r\n*\r\non(queryid, instance)\r\ngroup_left(query)\r\npg_stat_statements_query_id{instance=~\"$Instance\"}",
       "legendFormat": "{{datname}} : {{query}}"
      }
     ]
    },
    {
     "title": "Top 5 Queries by Total Execution Time ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "topk(5,\r\n  pg_stat_statements_seconds_total{datname=~\"$Database\", instance=~\"$Instance\"}\r\n)\r\n*\r\non(queryid, instance)\r\ngroup_left(query)\r\npg_stat_statements_query_id{instance=~\"$Instance\"}",
       "legendFormat": "{{datname}} : {{query}}"
      }
     ]
    },
    {
     "title": "Top 5 Most Frequent Queries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "topk(5,\r\n  increase(pg_stat_statements_calls_total{datname=~\"$Database\", instance=~\"$Instance\"}[1h])\r\n)\r\n*\r\non(queryid, instance)\r\ngroup_left(query)\r\npg_stat_statements_query_id{instance=~\"$Instance\"}",
       "legendFormat": "{{datname}} : {{query}}"
      }
     ]
    },
    {
     "title": "Total Queries Executed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum by (query) (\r\n  pg_stat_statements_calls_total{datname=~\"$Database\", instance=~\"$Instance\"}\r\n*\r\non(queryid, instance)\r\ngroup_left(query)\r\npg_stat_statements_query_id{instance=~\"$Instance\"}\r\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Database: $Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "Database" },
  {
   "title": "Database size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{instance=\"$Instance\",datname=\"$Database\"}"
    }
   ]
  },
  {
   "title": "Tuples inserts/updates/deletes",
   "type": "timeseries",
   "description": "Source: pg_stat_database",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{instance=\"$instance\",datname=\"$Database\"}[$Interval])",
     "legendFormat": "Inserts"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated{instance=\"$Instance\",datname=\"$Database\"}[$Interval])",
     "legendFormat": "Updates"
    },
    {
     "expr": "rate(pg_stat_database_tup_deleted{instance=\"$Instance\",datname=\"$Database\"}[$Interval])",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "1 Minute rate of transactions committed or rollback.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{instance=\"$instance\",datname=\"$Database\"}[$Interval])",
     "legendFormat": "committed"
    },
    {
     "expr": "rate(pg_stat_database_xact_rollback{instance=\"$Instance\",datname=\"$Database\"}[$Interval])",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "Locks by state",
   "type": "timeseries",
   "description": "Source: pg_locks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (mode) (pg_locks_count{instance=\"$Instance\",datname=\"$Database\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Tuples fetched/returned",
   "type": "timeseries",
   "description": "Source: pg_stat_database\n\n* tup_fetched: rows needed to satisfy queries\n* tup_returned: rows read/scanned",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched{instance=\"$Instance\",datname=\"$Database\"}[$Interval])",
     "legendFormat": "Fetched"
    },
    {
     "expr": "rate(pg_stat_database_tup_returned{instance=\"$Instance\",datname=\"$Database\"}[$Interval])",
     "legendFormat": "Returned"
    }
   ]
  },
  {
   "title": "Top 5 Most Frequent Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "topk(5,\r\n  increase(pg_stat_statements_calls_total{datname=~\"$Database\", instance=~\"$Instance\"}[1h])\r\n)\r\n*\r\non(queryid, instance)\r\ngroup_left(query)\r\npg_stat_statements_query_id{instance=~\"$Instance\"}",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Locks by state",
   "type": "timeseries",
   "description": "Source: pg_locks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (mode) (pg_locks_count{instance=\"$Instance\",datname=\"$Database\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Top 5 Slowest Queries by Average Time by base",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "topk(5,\r\n  (\r\n    pg_stat_statements_seconds_total{datname=~\"$Database\", instance=~\"$Instance\"}\r\n    /\r\n    pg_stat_statements_calls_total{datname=~\"$Database\", instance=~\"$Instance\"}\r\n  )\r\n)\r\n*\r\non(queryid, instance)\r\ngroup_left(query)\r\npg_stat_statements_query_id{instance=~\"$Instance\"}",
     "legendFormat": "{{datname}} : {{query}}"
    }
   ]
  }
 ]
}