{
 "title": "SRS Stat New version",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "zone", "query": { "query": "srs_build_info" } },
   { "name": "version", "query": { "query": "srs_build_info" } },
   { "name": "server_role", "query": { "query": "srs_build_info" } },
   { "name": "instance", "query": { "query": "srs_build_info" } }
  ]
 },
 "panels": [
  {
   "title": "All Online Servers",
   "type": "piechart",
   "description": "All Online Servers",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(srs_build_info{tag=~\"$server_role\",instance=~\"$instance\",label=~\"$zone\"})by(tag)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Version",
   "type": "piechart",
   "description": "Srs server version",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(srs_build_info{tag=~\"$server_role\",instance=~\"$instance\",label=~\"$zone\"})by(version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SRS Memory",
   "type": "timeseries",
   "description": "srs memory",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "srs_memory",
     "legendFormat": "memory usage by {{instance}}: pod {{pod}}"
    }
   ]
  },
  {
   "title": "Server Zones",
   "type": "piechart",
   "description": "Server zone distribution",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(srs_build_info{tag=~\"$server_role\",instance=~\"$instance\",label=~\"$zone\"})by(label)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "All Online Streams",
   "type": "stat",
   "description": "All Online Streams",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(srs_streams * on(pod) group_left(tag,label) srs_build_info {tag=~\"$server_role\",instance=~\"$instance\",label=~\"$zone\"})"
    }
   ]
  },
  {
   "title": "SRS Process CPU Percent",
   "type": "timeseries",
   "description": "srs process cpu percent",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "srs_cpu_percent",
     "legendFormat": "cpu (%) usage: instance {{instance}} / pod {{pod}}"
    }
   ]
  },
  {
   "title": "avg CPU (%) usage per pod ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(srs_cpu_percent)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "All Online Clients",
   "type": "stat",
   "description": "All Online Clients, include publish and play clients",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(srs_clients * on(pod) group_left(tag,label) srs_build_info{tag=~\"$server_role\",instance=~\"$instance\",label=~\"$zone\"})"
    }
   ]
  },
  { "title": "Online and errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Server Online streams",
   "type": "timeseries",
   "description": "Server Online streams",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "srs_streams * on(pod) group_left(tag,label) srs_build_info{tag=~\"$server_role\",instance=~\"$instance\",label=~\"$zone\"}"
    }
   ]
  },
  {
   "title": "Server Online Clients",
   "type": "timeseries",
   "description": "Display all server online clients, include publish and play clients",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "srs_clients * on(pod) group_left(tag,label) srs_build_info{tag=~\"$server_role\",instance=~\"$instance\",label=~\"$zone\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Srs Clients total",
   "type": "timeseries",
   "description": "Srs Clients total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "round(increase(srs_clients_total[5m]))\r\n* on(pod) group_left(tag,label,server,service,version)\r\n  max by(pod, tag, label, server, service, version) (\r\n    srs_build_info{\r\n      tag=~\"${server_role:regex}\",\r\n      instance=~\"${instance:regex}\",\r\n      label=~\"${zone:regex}\"\r\n    }\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "Srs Clients Err Total",
   "type": "timeseries",
   "description": "Srs Clients Err Total (5 minutes)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "round(increase(srs_clients_errs_total[5m]))\r\n* on(pod) group_left(tag,label)\r\n  srs_build_info{\r\n    tag=~\"${server_role:regex}\",\r\n    instance=~\"${instance:regex}\",\r\n    label=~\"${zone:regex}\"\r\n  }\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}