{
 "title": "Tusd Metrics",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "Instance",
    "query": {
     "query": "label_values({cluster=~\"$cluster\", job=\"integrations/tusd\"},instance)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values({cluster=~\"$cluster\", job=\"integrations/tusd\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory: Resident vs Allocated",
   "type": "timeseries",
   "description": " Сравнивает сколько Go-heap занимает и сколько реально занимает весь процесс",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}",
     "legendFormat": "{{instance}}  pod : {{pod}} : Resident Memory"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}",
     "legendFormat": "{{instance}}  pod : {{pod}} : Heap Allocated"
    }
   ]
  },
  {
   "title": "Process Start Time (hours)",
   "type": "gauge",
   "description": "старт tusd",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"} ) / 3600",
     "legendFormat": "{{instance}}  pod : {{pod}} "
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tusd_connections_open{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}",
     "legendFormat": "{{instance}} pod: {{pod}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "description": "доля времени, которое процесс тратит на GC (CPU-time на GC)",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}[5m]) * 100",
     "legendFormat": "{{instance}} pod : {{pod}}"
    }
   ]
  },
  {
   "title": "Go next GC heap target",
   "type": "timeseries",
   "description": "Объём heap-памяти, при достижении которого Go runtime запустит следующий garbage collection.\nНе отражает текущее потребление памяти.",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_next_gc_bytes{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}",
     "legendFormat": "{{instance}} pod : {{pod}}"
    }
   ]
  },
  {
   "title": "App Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}",
     "legendFormat": "{{instance}}  pod : {{pod}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "description": "Сетевой трафик ",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(process_network_receive_bytes_total{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{instance}} pod : {{pod}} Network Out (bytes/sec)"
    },
    {
     "expr": "rate(process_network_transmit_bytes_total{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{instance}} pod : {{pod}} Network Out (bytes/sec):{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Received (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(tusd_bytes_received{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{instance}}  pod : {{pod}} "
    }
   ]
  },
  {
   "title": "Tusd Uploads lifecycle",
   "type": "timeseries",
   "description": "Полная картина активности TUSD",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(tusd_uploads_created{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{instance}}  pod : {{pod}} : tusd_uploads_created"
    },
    {
     "expr": "rate(tusd_uploads_finished{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{instance}}  pod : {{pod}} : tusd_uploads_finished"
    },
    {
     "expr": "rate(tusd_uploads_terminated{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{instance}}  pod : {{pod}} : tusd_uploads_terminated"
    },
    {
     "expr": "rate(tusd_bytes_received{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{instance}}  pod : {{pod}} : tusd_bytes_received"
    }
   ]
  },
  {
   "title": "CPU Usage (rate)",
   "type": "timeseries",
   "description": "использование CPU by TUSD",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{instance}}  pod : {{pod}} "
    }
   ]
  },
  {
   "title": "Goroutines & Threads",
   "type": "timeseries",
   "description": "Слежение за количеством горутин и системных потоков.",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}",
     "legendFormat": "{{instance}}  pod : {{pod}} : Goroutines"
    },
    {
     "expr": "go_threads{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}",
     "legendFormat": "{{instance}}  pod : {{pod}} : OS Threads"
    }
   ]
  },
  {
   "title": "Heap & Stack Stats",
   "type": "timeseries",
   "description": "Разделение памяти Go между heap и stack.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}",
     "legendFormat": "{{instance}}  pod : {{pod}} : Heap Usage (bytes)"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}",
     "legendFormat": "{{instance}}  pod : {{pod}} : Stack Usage (bytes)"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Errors (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(tusd_errors_total{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{instance}}  pod : {{pod}} : {{code}}"
    }
   ]
  },
  {
   "title": "Total Requests (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(tusd_requests_total{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{instance}}  pod : {{pod}} : {{method}}"
    }
   ]
  },
  {
   "title": "HTTP S3 Request",
   "type": "timeseries",
   "description": "Среднюю продолжительность HTTP-запросов к S3.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(tusd_s3_request_duration_ms_sum{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}[5m]) ",
     "legendFormat": "{{instance}}  pod : {{pod}} : {{operation}}"
    }
   ]
  },
  { "title": "S3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "S3 Upload Semaphore Demand vs Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "tusd_s3_upload_semaphore_demand{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}",
     "legendFormat": "{{instance}}  pod : {{pod}} : demand"
    },
    {
     "expr": "tusd_s3_upload_semaphore_limit{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}",
     "legendFormat": "{{instance}}  pod : {{pod}} : limit"
    }
   ]
  },
  {
   "title": "S3 disk write latency (p99)",
   "type": "stat",
   "description": "99-й перцентиль длительности операций записи на диск в S3.\nПоказывает худшие 1% disk write операций и используется для выявления деградаций и длинных хвостов задержек.",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tusd_s3_disk_write_duration_ms{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\",  quantile=\"0.99\"}",
     "legendFormat": "{{instance}}  pod : {{pod}} : tusd Disk Write Time {{quantile}}"
    }
   ]
  },
  {
   "title": "S3 Disk Write Duration (Avg, ms)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tusd_s3_disk_write_duration_ms_sum / tusd_s3_disk_write_duration_ms_count {job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}\r\n",
     "legendFormat": "{{instance}}  pod : {{pod}}"
    }
   ]
  },
  {
   "title": "Request Duration (Avg, ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "(\r\n  rate(tusd_s3_request_duration_ms_sum{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}[$__interval_ms])\r\n)\r\n/\r\n(\r\n  rate(tusd_s3_request_duration_ms_count{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}[$__interval_ms])\r\n)",
     "legendFormat": "{{instance}}  pod : {{pod}} : {{operation}}"
    }
   ]
  },
  { "title": "Hooks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Hook Invocations (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "rate(tusd_hook_invocations_total{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{instance}}  pod : {{pod}} : {{hooktype}}"
    }
   ]
  },
  {
   "title": "Hook Errors (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "rate(tusd_hook_errors_total{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{instance}}  pod : {{pod}} : {{hooktype}}"
    }
   ]
  },
  {
   "title": "Hook Error Ratio",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "rate(tusd_hook_errors_total{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}[5m]) / rate(tusd_hook_invocations_total{job=\"integrations/tusd\", instance=~\"$Instance\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{instance}}  pod : {{pod}} : {{hooktype}}"
    }
   ]
  }
 ]
}