{
 "title": "Yandex queue",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "queue",
    "label": "queue",
    "query": {
     "query": "label_values(queue_messages_received_count_per_second{job=\"integrations/yandex\"},queue)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Count stored messages from queue",
   "type": "stat",
   "description": "Количество сообщений в очереди",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (queue) (\r\n  queue_messages_stored_count{job=\"integrations/yandex\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Oldest age of message in queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "queue_messages_oldest_age_milliseconds{queue=~\"$queue\"} / 1000",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Empty attempts to read from the queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (queue) (\r\n  rate(queue_messages_empty_receive_attempts_count_per_second{job=\"integrations/yandex\", queue=~\"$queue\"}[10m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (method) (\r\n  rate(api_http_requests_count_per_second{job=\"integrations/yandex\", queue=~\"$queue\"}[10m])\r\n)\r\n",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Number of deleted messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (queue) (\r\n  rate(queue_messages_deleted_count_per_second{job=\"integrations/yandex\", queue=~\"$queue\"}[5m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Errors, fails and etc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Empty receive attempts / sec",
   "type": "timeseries",
   "description": "показывает холостые запросы",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "queue_messages_empty_receive_attempts_count_per_second{queue=~\"$queue\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Request timeouts / sec",
   "type": "timeseries",
   "description": "Таймауты в очередях",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "queue_messages_request_timeouts_count_per_second{queue=~\"$queue\"}",
     "legendFormat": "timeout per {{queue}}"
    }
   ]
  },
  {
   "title": "Deleted vs Purged (stacked)",
   "type": "timeseries",
   "description": "удаленные пользователем или очередь чистится через purge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "queue_messages_deleted_count_per_second{queue=~\"$queue\"}",
     "legendFormat": "deleted messages in {{queue}}"
    },
    {
     "expr": "queue_messages_purged_count_per_second{queue=~\"$queue\"}",
     "legendFormat": "purged messages in {{queue}}"
    }
   ]
  }
 ]
}